# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0003_auto_20170329_1355'),
        ('beltTwo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='favs',
            new_name='quotes',
        ),
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_users', to='loginReg.User'),
            preserve_default=False,
        ),
    ]
